### ISSUE TITLE
Two State Logic LINT violations - el2_pdef.vh

### ISSUE THREAD

**Issue by nstewart-amd** [chipsalliance/Cores-VeeR-EL2#105]
├── el2_pdef.vh                             # Parameter structure definition

Values defined in el2_pdef.vh are defined as "bit", which is 2-state only variable.
Since standard verification flows wish to model "X" propagation, these variables should be multi-state "logic" instead of "bit".

Example:
    bit [7:0]      BHT_ADDR_HI;

Required for support for "X" propagation modelling in simulation:
    logic [7:0]      BHT_ADDR_HI;

**Comment by kiryk** [comment]
This was changed a while ago (https://github.com/chipsalliance/Cores-VeeR-EL2/commit/0ca2f4f7a), I'm closing the issue.
