### ISSUE TITLE
Swerv RISC V

### ISSUE THREAD

**Issue by navroops17** [chipsalliance/Cores-VeeR-EL2#137]
Hi 
I am trying to synthesize Swerv a RISC V and can anyone help me out how can I do it. Where to do and how to do.
Please

**Comment by mkurc-ant** [comment]
Hi.

The first thing to do is configuring VeeR. Please refer to the README.md (this point https://github.com/chipsalliance/Cores-VeeR-EL2#building-a-model) how to do that.

Following steps depend on the synthesis toolchain you use. The `flist` file (https://github.com/chipsalliance/Cores-VeeR-EL2/blob/main/design/flist) lists all VeeR sources needed for synthesis / simulation. You also need to add include path that points to the generated configuration (by default it generates under `snapshots/default`).

**Comment by mgielda** [comment]
Closing, assuming that this is solved.
