### ISSUE TITLE
CDC Error

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/Cores-VeeR-EL2#160]
Hi 

We are facing CDC issue as shown below:
![image](https://github.com/chipsalliance/Cores-VeeR-EL2/assets/143068047/a0d5cdf2-6d09-4f14-827e-73b6d4a40024)

Please check below schematic :
![image](https://github.com/chipsalliance/Cores-VeeR-EL2/assets/143068047/156749b4-2385-4507-a30d-f7163d549a9a)

We have added below constraints as mentioned in integration spec but still facing same issue:
![image](https://github.com/chipsalliance/Cores-VeeR-EL2/assets/143068047/6b88a7a7-8fac-4040-92e7-b86e8daedf36)

Do we need to add a synchronizer in the path, could you please help us to check?

**Comment by algrobman** [comment]
1) you can't use simple synchronizers to pass a bus to another clocking domain. You'll get bit divergence.
2) there is no need in the synchronizers for buses passing between TCK and CLK clocks domains. TAP controller and Debug Module (DM) logical designs guarantee that flops from both sides sample other side buses when they are stable. Read and Write control signals from TCK clock domain to DM are synchronized to the CPU CLK clock.

Specifically for this path dmi_reg_rdata from CLK clock domain is latched at one TCK clock, but sampled by JTAG SR register in different TCK clock. (TCK clock should be at least 2 times slower than CLK to make this circuit work reliably, which is normally a case - CPU is clocked by 100s MHz clock while TCK is  10MHz or less )
