### ISSUE TITLE
[bug] Case is not fully covered

### ISSUE THREAD

**Issue by likeamahoney** [chipsalliance/Cores-VeeR-EL2#280]
Hi! [Here](https://github.com/chipsalliance/Cores-VeeR-EL2/blob/b18a889775e59c3afa9fc99445686f449bfe0a66/testbench/dasm.svi#L49C7-L49C11) a `case` operator usage on 3 bit range value. 

But the `3'b100` value of the instruction opcode bits is not covered. Is this a typo or a bug?

**Comment by tmichalak** [comment]
Hi @likeamahoney, the code you linked to is used for decoding instructions from the the RISC-V "C" compressed instruction extension. When you look into the 16.8 RVC Instruction Set Listings chapter of the [Volume I: RISC-V Unprivileged ISA V20190608-Base-Ratified](https://riscv.org/wp-content/uploads/2019/06/riscv-spec.pdf) you will see that the `3'b100` opcode is reserved.
