### ISSUE TITLE
DCCM Region 0x0008_0000

### ISSUE THREAD

**Issue by KinzaQamar** [chipsalliance/Cores-VeeR-EL2#44]
Hi,
I was trying to load and store transactions through DCCM. The region address inside the document is 0x0008_0000 (page 17). But, I have noticed no change in transitions of DCCM signals.
Later, I found out that the starting and ending address of DCCM is 0xf0040000 to 0xf004ffff.
Is that a documentation error?

**Comment by tmichalak** [comment]
@KinzaQamar VeeR is configurable and the memory map can be altered using the `veer.config` script as described in the [README](https://github.com/chipsalliance/Cores-VeeR-EL2#configurations). The memory map in the documentation is just an example.
